-- Delivery and fulfillment tables.

CREATE TABLE IF NOT EXISTS vehicles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    driver_id UUID REFERENCES drivers (id) ON DELETE SET NULL,
    make TEXT,
    model TEXT,
    year INTEGER,
    color TEXT,
    license_plate TEXT,
    capacity_cubic_ft NUMERIC(8, 2),
    capacity_weight_lbs NUMERIC(8, 2),
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS delivery_runs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT,
    driver_id UUID REFERENCES drivers (id) ON DELETE SET NULL,
    vehicle_id UUID REFERENCES vehicles (id) ON DELETE SET NULL,
    scheduled_start TIMESTAMPTZ,
    scheduled_end TIMESTAMPTZ,
    actual_start TIMESTAMPTZ,
    actual_end TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS shipments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL UNIQUE REFERENCES orders (id) ON DELETE CASCADE,
    tracking_number TEXT UNIQUE,
    delivery_run_id UUID REFERENCES delivery_runs (id) ON DELETE SET NULL,
    status shipment_status NOT NULL DEFAULT 'pending',
    promised_arrival_at TIMESTAMPTZ,
    dispatched_at TIMESTAMPTZ,
    delivered_at TIMESTAMPTZ,
    cancelled_at TIMESTAMPTZ,
    last_status_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    current_driver_location_id BIGINT,
    current_driver_location_recorded_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS driver_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shipment_id UUID NOT NULL REFERENCES shipments (id) ON DELETE CASCADE,
    driver_id UUID REFERENCES drivers (id) ON DELETE SET NULL,
    status assignment_status NOT NULL DEFAULT 'pending',
    accepted_at TIMESTAMPTZ,
    declined_at TIMESTAMPTZ,
    en_route_at TIMESTAMPTZ,
    arrived_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    schedule_sequence INTEGER,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS route_stops (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shipment_id UUID NOT NULL REFERENCES shipments (id) ON DELETE CASCADE,
    assignment_id UUID REFERENCES driver_assignments (id) ON DELETE SET NULL,
    stop_type route_stop_type NOT NULL,
    position INTEGER NOT NULL,
    name TEXT,
    address JSONB,
    expected_arrival TIMESTAMPTZ,
    expected_departure TIMESTAMPTZ,
    actual_arrival TIMESTAMPTZ,
    actual_departure TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT route_stops_unique_position UNIQUE (shipment_id, position)
);

CREATE TABLE IF NOT EXISTS driver_location_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    driver_id UUID NOT NULL REFERENCES drivers (id) ON DELETE CASCADE,
    session_id UUID REFERENCES driver_sessions (id) ON DELETE SET NULL,
    assignment_id UUID REFERENCES driver_assignments (id) ON DELETE SET NULL,
    recorded_at TIMESTAMPTZ NOT NULL,
    latitude NUMERIC(10, 7) NOT NULL,
    longitude NUMERIC(10, 7) NOT NULL,
    accuracy NUMERIC(6, 2) CHECK (accuracy IS NULL OR (accuracy > 0 AND accuracy < 200)),
    speed NUMERIC(6, 2),
    heading NUMERIC(6, 2),
    altitude NUMERIC(8, 2),
    battery_level NUMERIC(4, 2),
    source driver_location_source NOT NULL DEFAULT 'background',
    is_gps BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id)
) PARTITION BY RANGE (recorded_at);

CREATE TABLE IF NOT EXISTS shipment_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    shipment_id UUID NOT NULL REFERENCES shipments (id) ON DELETE CASCADE,
    driver_id UUID REFERENCES drivers (id) ON DELETE SET NULL,
    assignment_id UUID REFERENCES driver_assignments (id) ON DELETE SET NULL,
    location_event_id BIGINT,
    event_type shipment_event_type NOT NULL,
    status shipment_status,
    eta TIMESTAMPTZ,
    description TEXT,
    details JSONB NOT NULL DEFAULT '{}'::JSONB,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
) PARTITION BY RANGE (occurred_at);

ALTER TABLE shipment_events
    ADD CONSTRAINT shipment_events_location_event_fk
    FOREIGN KEY (location_event_id) REFERENCES driver_location_events (id)
    ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS tracking_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    customer_id UUID REFERENCES customers (id) ON DELETE SET NULL,
    session_token UUID NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT tracking_sessions_unique_token UNIQUE (order_id, session_token)
);

ALTER TABLE shipments
    ADD CONSTRAINT shipments_current_location_fk
    FOREIGN KEY (current_driver_location_id) REFERENCES driver_location_events (id)
    ON DELETE SET NULL;

